[package]
name = "crypto-playground"
version = "0.1.0"
authors = ["Stanimal <sdbondi@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.33"
web-view = "0.4.0"